baseURL = "https://brainworms.dev"
languageCode = "en-us"
title = "brainworms.dev"
theme="archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	useCDN=false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/leander-elw"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About the author"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4
